### ISSUE TITLE
Not enough scrolling

### ISSUE THREAD

**Issue by erikthiem** [Esaron/trash-panda#11]

**Comment by jpodonnell** [comment]
not enough info, please elaborate

**Comment by jpodonnell** [comment]
@erikthiem please give more detail

**Comment by erikthiem** [comment]
As a 
![image](https://user-images.githubusercontent.com/204945/40790008-c469b8ea-64c1-11e8-828d-5c837054a8ed.png),
I would like to see more full-page scrolling. I think it would help with visual appeal.

**Comment by Esaron** [comment]
Shame.

**Comment by bryceglass** [comment]
@erikthiem i expect that by the time we flesh out our skeleton site w/actual content, it will occasion a certain amount of scrolling on teh part of our users.
