### ISSUE TITLE
Image Gallery

### ISSUE THREAD

**Issue by tvon** [Esaron/trash-panda#2]
The site should include an image gallery with variouspictures of the aimal.

* The gallery is part of the overall site navigation
* At least 4 difeerent pictures of the animal
* Each picture appears on it's own page
* Each picture has a caption and accompanying text where appropriate
* Somewhere in the gallery we ask site visitors to submit their own pictures

**Comment by bryceglass** [comment]
Here are a variety of attractive Trash Panda images.

![59561066699cf_rc7girs__700](https://user-images.githubusercontent.com/829556/40787150-e62f63b4-64ba-11e8-8d09-02d858c58eff.jpg)
![adorable-cute-raccoons-1-59560d2d0e26f__700](https://user-images.githubusercontent.com/829556/40787151-e64275da-64ba-11e8-8e9c-35e49c75fbfb.jpg)
![adorable-cute-raccoons-66-59563d8b8304f__700](https://user-images.githubusercontent.com/829556/40787152-e652c64c-64ba-11e8-87da-2cce42e1fead.jpg)
![adorable-cute-raccoons-68-595642de22445__700](https://user-images.githubusercontent.com/829556/40787153-e6688306-64ba-11e8-8032-6a7f615fe547.jpg)

**Comment by bryceglass** [comment]
And here's the ZIP of all of them.. (please don't make me remember GIT cmds..) 

[Trash Pandas.zip](https://github.com/Esaron/trash-panda/files/2058548/Trash.Pandas.zip)

**Comment by tvon** [comment]
I think we can probably just link to the images here in the github pages.
