### ISSUE TITLE
Diet information

### ISSUE THREAD

**Issue by tvon** [Esaron/trash-panda#3]
The site has a dedicated page to explain the dietary habits of the animal.

* The page is part of the overall site naviation
* The page has details about what the animal eats, how often, and what amounts.
* The page may link out to external resources with more detail on individual food items.

**Comment by bryceglass** [comment]
Please update content for this section to: 

> The Trash Panda is an omnivorous and opportunistic eater, with its diet determined heavily by its environment. Common foods include fruits, plants, nuts, berries, insects, rodents, frogs, eggs, and crayfish. In urban environments, the animal often sifts through garbage for food.
