### ISSUE TITLE
Monetize with ad revenue

### ISSUE THREAD

**Issue by tvon** [Esaron/trash-panda#32]
We need to find a kid-friendly advertising network to embed ads on our pages. Here's [a good Quora thread with suggestions](https://www.quora.com/Which-is-the-best-children-friendly-AD-network-except-AdSense-for-a-Linux-releated-website).

Based on advice from that page.. let's incorporate https://chitika.com/ Ads. (**NB:** this would require us actually signing up for a Chitika account, which is probably pretty involved. We may end up dropping this feature if it's looking too involved.)

**Comment by Esaron** [comment]
In a few short months, we'll be rolling in cents.
