### ISSUE TITLE
'Copy' text functionality

### ISSUE THREAD

**Issue by bryceglass** [Esaron/trash-panda#35]
For kids that don't know Cmd-C, lets have a way to select text and then copy it to clipboard with one click.

**Comment by davidhatten** [comment]
For examples, see Amazon Kindle select text context, and Safari Books Online select text context

**Comment by bryceglass** [comment]
Thanks @Esaron  — please @-mention me when this is ready for review. I'll move it to 'Done'

**Comment by Esaron** [comment]
@bryceglass Ready for review. Click on a paragraph and get an alert. Horrible UX, but hey, it's done.

**Comment by Esaron** [comment]
^ Pretend like you did the moving/closing
