### ISSUE TITLE
Embed the Image Gallery

### ISSUE THREAD

**Issue by bryceglass** [Esaron/trash-panda#36]
We'd like to present our IMGUR gallery as a more-integrated 'widget' or part of the site (not launching into external site w/new tab)

**Comment by tvon** [comment]
Embed code for [album](https://imgur.com/a/hTV4twf): 
```
<blockquote class="imgur-embed-pub" lang="en" data-id="a/hTV4twf"><a href="//imgur.com/a/hTV4twf">View post on imgur.com</a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>
```

**Comment by bryceglass** [comment]
Thanks @tvon  — please @-mention me when this is ready for review. I'll move it to 'Done'
