### ISSUE TITLE
Mating and Reproduction Information

### ISSUE THREAD

**Issue by tvon** [Esaron/trash-panda#4]
The site has a page dedicated to mating and reproductino facts bout the animals.

* The page is part of the overall site navigation
* The page answers the following questions and includes any other relevant facts:
  * What ist he gestational period of the animal.
  * How long do the offspring live with the parent.

**Comment by bryceglass** [comment]
Content:

> Trash Pandas mate in the late winter or early spring. The gestation period is approximately 63 days. Females give birth to the annual litter of 1-8 (average 2-5) in the den, which in the case of tree cavities, may contain sparse bedding of shredded wood.

**Comment by bryceglass** [comment]
This looks greeat! Closing it out..
