### ISSUE TITLE
Animal Habitat Information

### ISSUE THREAD

**Issue by tvon** [Esaron/trash-panda#5]
The site has a page dedicated to the natural habitat of the animal.

* The page is part of the overall site navigation
* The site answers tthe following questions and includes any other relevant facts.
* Where on earth is the animal found.
* What natural surroundings does the animal need to thrive?
* Where does the animal make it's home?
  * in the ground
  * in a tree
  * other..?

**Comment by bryceglass** [comment]
Content:

> Traditionally, Trash Pandas prefer heavily **wooded** areas with access to trees, water and abundant vegetation. There, they make their dens in the hollow parts of trees as well as abandoned burrows, traveling up to 18 miles to forage for food. Trash Pandas are extremely adaptable.
