### ISSUE TITLE
Animal Anatomy and Biology

### ISSUE THREAD

**Issue by tvon** [Esaron/trash-panda#7]
The site should include a page dedicated to the overall anatomy and biology of the animal.

* The page is part of the overall site navigation
* Include information on the following, as well as any other interesting and reletive facts:
  * Height / weight / general size information
  * How the animal breathes
  * How long the average animal of this species lives

**Comment by bryceglass** [comment]
Please add the following text to this section: 

> The Trash Panda (Procyon lotor), also called “racoon,” is a stocky mammal about 2 to 3 feet (61 to 91 cm) long, weighing 10 to 30 pounds (4.5 to 13.5 kg) (rarely 40 to 50 pounds [18 to 22.5 kg]). It is distinctively marked, with a prominent black “mask” over the eyes and a heavily furred, ringed tail. The animal is a grizzled salt-and-pepper gray and black above, although some individuals are strongly washed with yellow. Trash Pandas from the prairie areas of the western Great Plains are paler in color than those from eastern portions of the region.
