### ISSUE TITLE
Animal Behavior

### ISSUE THREAD

**Issue by tvon** [Esaron/trash-panda#8]
The site should include a page dedicated to the overall behavior of the animal:

* The page is part of the overall site navigation
* Include information on the following, as well as any other interesting and relative facts:
  * How the animal gets food
  * How the animal protects itself from predators
  * Sleeping habits

**Comment by tvon** [comment]
## How they get food

Trash Pandas are known to upcycle food discarded by other animals, particularly humans.

**Comment by bryceglass** [comment]
More hot Behavioral content: 

> **Nocturnal** in nature, raccoons are mostly active at nighttime. They are most active in spring, summer and fall, and will **sleep** in their dens for most of the winter. Reproduction: Reproduction begins in late winter.

**Comment by bryceglass** [comment]
This looks great — I'm moving to 'Done' and closing it out.
